--- #YAML:1.0
name:                Eidolon-Driver-Router-Consequent
version:             0.01
abstract:            consequent request router for Eidolon.
license:             ~
author:              
    - Anton Belousov <abel@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Eidolon:                       0.02
    List::Util:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
